name: Publish Manga to Blogger

on:
  schedule:
    - cron: '0 * * * *'  # يشغل الكود كل ساعة. يمكنك تعديل الجدول حسب احتياجاتك.
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests feedparser google-auth

    - name: Run script
      env:
        BLOG_ID: ${{ secrets.BLOGGER_BLOG_ID }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      run: |
        python script.py
