name: Publish Website Content to Blogger

on:
  schedule:
    - cron: '0 0 * * *'  # هذا الجدول يقوم بتشغيل العمل مرة كل يوم في منتصف الليل
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Fetch Website Content
        env:
          WEBSITE_URL: ${{ secrets.WEBSITE_URL }}
        run: |
          python fetch_website_content.py

      - name: Publish to Blogger
        env:
          BLOGGER_API_KEY: ${{ secrets.BLOGGER_API_KEY }}
          BLOGGER_BLOG_ID: ${{ secrets.BLOGGER_BLOG_ID }}
        run: |
          python publish_to_blogger.py
